package com.application.enums;

public enum GeoForcaVendasScriptEnum {
    TABELA_DE_PRECO(10, "Tabela de Preço"),
    TABELA_DE_PRECO_POR_REPRESENTANTE(15, "Tabela de Preço por Representante"),
    TABELA_DE_PRECO_POLITICA(17, "Tabela de Preço - Política"),
    TABELA_DE_PRECO_PRODUTO(20, "Tabela de Preço - Produto"),
    TABELA_DE_PRECO_SKU(20001, "Tabela de Preço - SKU"),
    TABELA_DE_PRECO_COLECAO_DE_PARA(21, "Tabela de Preço - Coleção De/Para"),
    TABELA_DE_PRECO_REPRESENTANTE_DE_PARA(22, "Tabela de Preço - Representante De/Para"),
    TABELA_DE_PRECO_CLIENTE_DE_PARA(23, "Tabela de Preço - Cliente De/Para"),
    TABELA_DE_PRECO_POLITICA_DESCONTO_COMERCIAL(24, "Tabela de Preço - Política - Desconto Comercial"),
    TABELA_DE_PRECO_POLITICA_DESCONTO_FINANCEIRO(25, "Tabela de Preço - Política - Desconto Financeiro"),
    TABELA_DE_PRECO_POLITICA_DESCONTO_ANTECIPACAO(26, "Tabela de Preço - Política - Desconto Antecipação"),
    TABELA_DE_PRECO_POLITICA_PRAZO_ADICIONAL(27, "Tabela de Preço - Política - Prazo Adicional"),
    TABELA_DE_PRECO_POLITICA_CAPA(28, "Tabela de Preço - Política - Capa"),
    TABELA_DE_PRECO_POLITICA_DESCONTO_12_ACRESCIMO_FINANCEIRO(29, "Tabela de Preço - Política - Desconto 12 - Acréscimo Financeiro"),
    TABELA_DE_PRECO_POLITICA_DESCONTO_13_SEGMENTO(29001, "Tabela de Preço - Política - Desconto 13 - Segmento"),
    TABELA_DE_PRECO_POLITICA_DESCONTO_12_ADICIONAL_LOTE(29002, "Tabela de Preço - Política - Desconto 12 - Adicional Lote"),
    TABELA_DE_PRECO_POLITICA_FAIXAS_PRAZO_MEDIO(29003, "Tabela de Preço - Política - Faixas Prazo Médio"),
    TITULOS(30, "Títulos"),
    CONDICAO_DE_VENDA(40, "Condição de Venda"),
    TIPO_DE_NOTA(50, "Tipo de Nota"),
    PORTADOR(53, "Portador"),
    TIPO_DE_ENTREGA(55, "Tipo de Entrega"),
    TIPO_DE_COBRANCA(57, "Tipo de Cobrança"),
    COMISSOES(60, "Comissões"),
    COMISSOES_EXTRATO_RESUMO(63, "Comissões - Extrato Resumo"),
    COMISSOES_EXTRATO_DETALHADO(65, "Comissões - Extrato Detalhado"),
    COMISSOES_EXTRATO_V2_RESUMO(67, "Comissões - Extrato V2 Resumo"),
    COMISSOES_EXTRATO_V2_DETALHADO(68, "Comissões - Extrato V2 Detalhado"),
    COTA_DE_ESTOQUE_POR_REPRESENTANTE(69, "Cota de estoque - Por representante"),
    CLIENTES(70, "Clientes"),
    CLIENTES_POR_CNPJ(71, "Clientes por CNPJ"),
    CLIENTES_REFERENCIAS_COMERCIAIS(72, "Clientes - Referências Comercias"),
    CLIENTES_CONTATOS(73, "Clientes - Contatos"),
    CLIENTES_CAMPOS_CUSTOMIZADOS(74, "Clientes - Campos Customizados"),
    CLIENTES_LOCAIS_DE_ENTREGA(75, "Clientes - Locais de Entrega"),
    CLIENTES_TRIANGULACAO(7501, "Clientes - Triangulação"),
    CLIENTES_CONDICOES_DE_VENDA(7601, "Clientes - Condições de venda"),
    RAMOS_DE_ATIVIDADE(76, "Ramos de Atividade"),
    GRUPOS_DE_CLIENTE(77, "Grupos de Cliente"),
    MARCAS(7701, "Marcas"),
    MARCAS_CONCORRENTES(7702, "Marcas Concorrentes"),
    CLIENTES_RECORRENTES(78, "Clientes Recorrentes"),
    CLIENTES_CONTATOS_DEPARTAMENTO(79, "Clientes - Contatos - Departamento"),
    PRODUTOS(80, "Produtos"),
    PRODUTOS_GRADES(83, "Produtos - Grades"),
    PRODUTOS_SORTIMENTOS(85, "Produtos - Sortimentos"),
    PRODUTOS_FAMILIA_SORTIMENTOS(86, "Produtos - Família Sortimentos"),
    PRODUTOS_CODIGO_REDUZIDO(87, "Produtos - Código Reduzido"),
    PRODUTOS_CODIGOS_EAN13(88, "Produtos - Códigos EAN13"),
    PRODUTOS_IMAGENS_B2SPREFERENCIAIMAGEM(80001, "Produtos - Imagens - B2S Preferência Imagem"),
    BLOQUEIO_DE_REFERENCIAS(89, "Bloqueio de Referências"),
    PRODUTOS_LINHAS(90, "Produtos - Linhas"),
    PRODUTOS_ETIQUETAS(92, "Produtos - Etiquetas"),
    PRODUTOS_GENERO(93, "Produtos - Gênero"),
    PRODUTOS_MODELOS(94, "Produtos - Modelos"),
    PRODUTOS_TIPOS(96, "Produtos - Tipos"),
    PRODUTOS_SKUS(97, "Produtos - SKUs"),
    PRODUTOS_KEYWORDS(98, "Produtos - Keywords"),
    PRODUTOS_UNIDADE_MEDIDA(99, "Produtos - Unidade de Medida"),
    PEDIDOS_CAPA(100, "Pedidos - Capa"),
    PEDIDOS_POR_REFERENCIA(115, "Pedidos - Por Referência"),
    PEDIDOS_UUID(130, "Pedidos - UUID"),
    PEDIDOS_UUID_EM_MASSA(135, "Pedidos - UUID em Massa"),
    LISTAGEM_DE_PEDIDOS_CAPA(140, "Listagem de Pedidos - Capa"),
    LISTAGEM_DE_PEDIDOS_EM_ABERTO_CAPA(141, "Listagem de Pedidos em Aberto - Capa"),
    LISTAGEM_DE_PEDIDOS_DETALHADO(150, "Listagem de Pedidos - Detalhado"),
    LISTAGEM_DE_PEDIDOS_EM_ABERTO_DETALHADO(151, "Listagem de Pedidos em Aberto - Detalhado"),
    LISTAGEM_DE_PEDIDOS_ITENS(160, "Listagem de Pedidos - Itens"),
    LISTAGEM_DE_PEDIDOS_ITENS_GRADE(161, "Listagem de Pedidos - Itens - Grade"),
    LISTAGEM_DE_PEDIDOS_EM_ABERTO_ITENS(162, "Listagem de Pedidos em Aberto - Itens"),
    LISTAGEM_DE_PEDIDOS_NOTAS(170, "Listagem de Pedidos - Notas"),
    LISTAGEM_DE_PEDIDOS_OBSERVACOES(171, "Listagem de Pedidos - Observações"),
    LISTAGEM_DE_PEDIDOS_HISTORICO(172, "Listagem de Pedidos - Histórico"),
    LISTAGEM_DE_NOTAS_FISCAIS_CAPA(180, "Listagem de Notas Fiscais - Capa"),
    ESTOQUE_ONLINE(200, "Estoque Online"),
    ESTOQUE_ONLINE_LISTA_DE_ITENS_NO_PARAMETRO(201, "Estoque Online - Lista de Itens no Parâmetro"),
    ESTOQUE_ONLINE_REPRESENTANTE(202, "Estoque Online - Representante"),
    ESTOQUE_CONTA_CORRENTE(205, "Estoque - Conta Corrente"),
    ROMANEIO_SEARCHOBJ(210, "Romaneio - SearchObj"),
    ROMANEIO_ITENS(215, "Romaneio - Itens"),
    LOTES_DE_ENTREGA(220, "Lotes de Entrega"),
    LOTES_DE_FATURAMENTO(221, "Lotes de Faturamento"),
    COMPRA_ACUMULADA_VALORES_BASE_CALCULO(230, "Compra Acumulada - Valores Base Cálculo"),
    COMPRA_ACUMULADA_POLITICA_DE_DESCONTOS(231, "Compra Acumulada - Política de Descontos"),
    FAIXA_CRESCIMENTO_VALORES_BASE_CALCULO_COLECAO_ANTERIOR(240, "Faixa de Crescimento - Valores Base Cálculo - Coleção Anterior"),
    FAIXA_CRESCIMENTO_VALORES_BASE_CALCULO_COLECAO_ATUAL(241, "Faixa de Crescimento - Valores Base Cálculo - Coleção Atual"),
    FAIXA_CRESCIMENTO_POLITICA_DE_DESCONTOS(242, "Faixa de Crescimento - Política de Descontos"),
    VOLUME_COMPRA_POLITICA_DE_DESCONTOS(250, "Volume de Compra - Política de Descontos"),
    DESCONTO_CAMPANHA_POLITICA_DE_DESCONTOS(251, "Desconto de Campanha - Política de Descontos"),
    DESCONTO_LINHA_DE_PRODUTO_POLITICA_DE_DESCONTOS(252, "Desconto - Linha de Produto - Política de Descontos"),
    TIPO_CLIENTE(260, "Tipo de Cliente"),
    INDICADOR_FISCAL(261, "Indicador Fiscal"),
    POLITICA_COLECAO(341, "Política - Coleção"),
    PROGRAMA_CASHBACK_PARAMETROS(400, "Programa Cashback - Parâmetros"),
    PROGRAMA_CASHBACK_VALORES_BASE_CALCULO(401, "Programa Cashback - Valores Base Cálculo"),
    CALCULO_DE_ST_POR_PRODUTO_PARAMETROS(402, "Cálculo de ST por Produto - Parâmetros"),
    CALCULO_DE_ST_POR_PRODUTO_GRUPOS_DE_CLIENTE(403, "Cálculo de ST por Produto - Grupos de Cliente"),
    SUGESTAO_DE_DESCONTOS(430, "Sugestão de Descontos"),
    CONTA_CORRENTE(431, "Conta Corrente"),
    CONTA_CORRENTE_SITUACAO_PEDIDO(432, "Conta Corrente - Situação do Pedido"),
    SKUS_PRONTA_ENTREGA_E_PROGRAMADO(444, "SKUs - Pronta Entrega e Programado"),
    TABELA_DE_PRECO_POLITICA_PRECO_POR_VOLUME(450, "Tabela de Preço - Política - Preço por Volume"),
    TAMANHOS(500, "Tamanhos"),
    VALOR_DE_FRETE(555, "Valor de Frete"),
    CLIENTES_TIPO_NOTA(776, "Clientes - Tipo de Nota"),
    PEDIDOS_POR_DATA_DE_LOTE_FATUR(800, "Pedidos - Por Data de Lote Fatur."),
    INTERNACIONALIZACAO_REFERENCIAS(801, "Internacionalização - Referências"),
    INTERNACIONALIZACAO_CORES(802, "Internacionalização - Cores"),
    INTERNACIONALIZACAO_COLECOES(803, "Internacionalização - Coleções"),
    INTERNACIONALIZACAO_TIPOS_DE_PRODUTO(804, "Internacionalização - Tipos de Produto"),
    INTERNACIONALIZACAO_MODELOS_DE_PRODUTO(805, "Internacionalização - Modelos de Produto"),
    INTERNACIONALIZACAO_MARCAS_DE_PRODUTO(806, "Internacionalização - Marcas de Produto"),
    INTERNACIONALIZACAO_LINHAS_DE_PRODUTO(807, "Internacionalização - Linhas de Produto"),
    INTERNACIONALIZACAO_STATUS_DE_PEDIDOS(808, "Internacionalização - Status de Pedidos"),
    CLASSIFICACAO_DE_PEDIDOS(810, "Classificação de Pedidos"),
    CLIENTES_INDICADORES(809, "Clientes - Indicadores"),
    CLIENTES_REPOSICAO(811, "Clientes - Reposição"),
    ACESSORIOS_PRODUTOS(901, "Acessórios - Produtos"),
    LA_BELLA_MAFIA_CLIENTES_PARA_ATUALIZAR(902, "La Bella Mafia - Clientes para Atualizar"),
    PRODUTOS_GOLD_BE(903, "Produtos - Gold Be"),
    PRODUTOS_PARTE_CIMA_PARTE_BAIXO(904, "Produtos - Parte Cima/Parte Baixo"),
    PRODUTOS_DATA_DE_ENTREGA(905, "Produtos - Data de Entrega"),
    PRODUTOS_PRIORIDADE_DE_LINHA_PARA_DISTRIBUICAO(910, "Produtos - Prioridade de Linha para Distribuição");

    private final int value;
    private final String description;

    GeoForcaVendasScriptEnum(int value, String description) {
        this.value = value;
        this.description = description;
    }

    public int getValue() {
        return value;
    }

    public String getDescription() {
        return description;
    }
}
